[package]
name = "nbody"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
fastrand = "2.3.0"
macroquad = "0.4.13"
zorder = "0.2.2"
ultraviolet = { version = "0.9.2", features = ["int"] }
